### ISSUE TITLE
Add Condition to check usage for particular discount

### ISSUE THREAD

**Issue by tejalgandhi13** [immera/ecom-discount#3]
``suggestion```
Add discount id condition for check usage particular discount
https://github.com/immera/ecom-discount/blob/f252ae060ccf456b2b4170d1e9bcc0604ff63984/src/service/Validations/UsageValidation.php#L17

$count = DiscountCouponUsage::where('discountee_id', $this->user->getId())->where('discount_id',$this->discount->id)->count();

**Comment by hk2cmpny** [comment]
@tejalgandhi13 Thanks for notify this is a real issue, I've provided the fix in the [PR#4](https://github.com/immera/ecom-discount/pull/4)
